# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{joint}
  s.version = "0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John Nunemaker"]
  s.date = %q{2010-03-26}
  s.description = %q{MongoMapper and GridFS united in file upload love.}
  s.email = %q{nunemaker@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "Rakefile",
     "lib/joint.rb",
     "lib/joint/version.rb",
     "test/fixtures/mr_t.jpg",
     "test/fixtures/unixref.pdf",
     "test/helper.rb",
     "test/test_joint.rb"
  ]
  s.homepage = %q{http://github.com/jnunemaker/joint}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{MongoMapper and GridFS united in file upload love.}
  s.test_files = [
    "test/fixtures",
     "test/fixtures/mr_t.jpg",
     "test/fixtures/unixref.pdf",
     "test/helper.rb",
     "test/test_joint.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<wand>, [">= 0.2.1"])
      s.add_runtime_dependency(%q<mime-types>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<mongo_mapper>, [">= 0"])
    else
      s.add_dependency(%q<wand>, [">= 0.2.1"])
      s.add_dependency(%q<mime-types>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<mongo_mapper>, [">= 0"])
    end
  else
    s.add_dependency(%q<wand>, [">= 0.2.1"])
    s.add_dependency(%q<mime-types>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<mongo_mapper>, [">= 0"])
  end
end

